Update task-build-artifacts.yml

diff --git a/.github/workflows/task-build-artifacts.yml b/.github/workflows/task-build-artifacts.yml
--- a/.github/workflows/task-build-artifacts.yml
+++ b/.github/workflows/task-build-artifacts.yml
@@ -192,63 +192,63 @@ jobs:
         env:
           COORD: oss
         run: ${{ env.BUILD_CMD }} && make pack
-      - name: Build and Pack RediSearch Lite
-        env:
-          LITE: 1
-        run: ${{ env.BUILD_CMD }} && make pack
-      - name: Build and Pack RediSearch Enterprise
-        env:
-          COORD: rlec
-          MAX_WORKER_THREADS: ${{ vars.MAX_WORKER_THREADS }}
-        run: ${{ env.BUILD_CMD }} && make pack
+      # - name: Build and Pack RediSearch Lite
+      #   env:
+      #     LITE: 1
+      #   run: ${{ env.BUILD_CMD }} && make pack
+      # - name: Build and Pack RediSearch Enterprise
+      #   env:
+      #     COORD: rlec
+      #     MAX_WORKER_THREADS: ${{ vars.MAX_WORKER_THREADS }}
+      #   run: ${{ env.BUILD_CMD }} && make pack
 
       # Upload
-      - name: Configure AWS Credentials Using Role (node20)
-        if: vars.USE_AWS_ROLE == 'true' && steps.node20.outputs.supported == 'true'
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ vars.ARTIFACT_UPLOAD_AWS_ROLE_TO_ASSUME }}
-          aws-region: ${{ vars.ARTIFACT_UPLOAD_AWS_REGION }}
-      - name: Configure AWS Credentials Using Role (node20 not supported)
-        if: vars.USE_AWS_ROLE == 'true' && steps.node20.outputs.supported == 'false'
-        run: |
-          # Variables from the workflow
-          ROLE_ARN="${{ vars.ARTIFACT_UPLOAD_AWS_ROLE_TO_ASSUME }}"
-          AWS_REGION="${{ vars.ARTIFACT_UPLOAD_AWS_REGION }}"
-          SESSION_NAME="github-actions-session"
+      # - name: Configure AWS Credentials Using Role (node20)
+      #   if: vars.USE_AWS_ROLE == 'true' && steps.node20.outputs.supported == 'true'
+      #   uses: aws-actions/configure-aws-credentials@v4
+      #   with:
+      #     role-to-assume: ${{ vars.ARTIFACT_UPLOAD_AWS_ROLE_TO_ASSUME }}
+      #     aws-region: ${{ vars.ARTIFACT_UPLOAD_AWS_REGION }}
+      # - name: Configure AWS Credentials Using Role (node20 not supported)
+      #   if: vars.USE_AWS_ROLE == 'true' && steps.node20.outputs.supported == 'false'
+      #   run: |
+      #     # Variables from the workflow
+      #     ROLE_ARN="${{ vars.ARTIFACT_UPLOAD_AWS_ROLE_TO_ASSUME }}"
+      #     AWS_REGION="${{ vars.ARTIFACT_UPLOAD_AWS_REGION }}"
+      #     SESSION_NAME="github-actions-session"
 
-          # Assume the AWS role and configure temporary credentials
-          ASSUME_ROLE_OUTPUT=$(aws sts assume-role --role-arn "$ROLE_ARN" --role-session-name "$SESSION_NAME" --region "$AWS_REGION")
-          if [ $? -ne 0 ]; then
-            echo "Failed to assume AWS role" && exit 1
-          fi
+      #     # Assume the AWS role and configure temporary credentials
+      #     ASSUME_ROLE_OUTPUT=$(aws sts assume-role --role-arn "$ROLE_ARN" --role-session-name "$SESSION_NAME" --region "$AWS_REGION")
+      #     if [ $? -ne 0 ]; then
+      #       echo "Failed to assume AWS role" && exit 1
+      #     fi
 
-          echo "AWS credentials configured successfully."
-      - name: Configure AWS Credentials Using Keys (node20)
-        if: vars.USE_AWS_ROLE == 'false' && steps.node20.outputs.supported == 'true'
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.ARTIFACT_UPLOAD_AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.ARTIFACT_UPLOAD_AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ vars.ARTIFACT_UPLOAD_AWS_REGION }}
-      - name: Configure AWS Credentials Using Keys (node20 not supported)
-        if: vars.USE_AWS_ROLE == 'false' && steps.node20.outputs.supported == 'false'
-        run: |
-          # Variables from the workflow
-          AWS_ACCESS_KEY_ID="${{ secrets.ARTIFACT_UPLOAD_AWS_ACCESS_KEY_ID }}"
-          AWS_SECRET_ACCESS_KEY="${{ secrets.ARTIFACT_UPLOAD_AWS_SECRET_ACCESS_KEY }}"
-          AWS_REGION="${{ vars.ARTIFACT_UPLOAD_AWS_REGION }}"
+      #     echo "AWS credentials configured successfully."
+      # - name: Configure AWS Credentials Using Keys (node20)
+      #   if: vars.USE_AWS_ROLE == 'false' && steps.node20.outputs.supported == 'true'
+      #   uses: aws-actions/configure-aws-credentials@v4
+      #   with:
+      #     aws-access-key-id: ${{ secrets.ARTIFACT_UPLOAD_AWS_ACCESS_KEY_ID }}
+      #     aws-secret-access-key: ${{ secrets.ARTIFACT_UPLOAD_AWS_SECRET_ACCESS_KEY }}
+      #     aws-region: ${{ vars.ARTIFACT_UPLOAD_AWS_REGION }}
+      # - name: Configure AWS Credentials Using Keys (node20 not supported)
+      #   if: vars.USE_AWS_ROLE == 'false' && steps.node20.outputs.supported == 'false'
+      #   run: |
+      #     # Variables from the workflow
+      #     AWS_ACCESS_KEY_ID="${{ secrets.ARTIFACT_UPLOAD_AWS_ACCESS_KEY_ID }}"
+      #     AWS_SECRET_ACCESS_KEY="${{ secrets.ARTIFACT_UPLOAD_AWS_SECRET_ACCESS_KEY }}"
+      #     AWS_REGION="${{ vars.ARTIFACT_UPLOAD_AWS_REGION }}"
 
-          # Check if the required environment variables are set
-          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_REGION" ]; then
-            echo "Missing AWS credentials or region configuration."
-            exit 1
-          fi
+      #     # Check if the required environment variables are set
+      #     if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_REGION" ]; then
+      #       echo "Missing AWS credentials or region configuration."
+      #       exit 1
+      #     fi
 
-          # Configure AWS CLI with provided credentials and region
-          echo "Configuring AWS CLI with access keys..."
-          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
-          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
-          aws configure set region "$AWS_REGION"
-      - name: Upload Artifacts
-        run: make upload-artifacts
+      #     # Configure AWS CLI with provided credentials and region
+      #     echo "Configuring AWS CLI with access keys..."
+      #     aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
+      #     aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
+      #     aws configure set region "$AWS_REGION"
+      # - name: Upload Artifacts
+      #   run: make upload-artifacts
